import { Product, QuoteRequestSummary, OrderSummary, ActivityItem, ArtisanProfile } from "../services/types";

export const mockArtisanProfile: ArtisanProfile = {
  id: "550e8400-e29b-41d4-a716-446655440000",
  business_name: "Sita's Rural Craft Collective",
  craft_type: "Handwoven Jute & Terracotta",
  description: "Authentic sustainable handcrafted products made by women artisans of rural Rajasthan.",
  location: "Barmer, Rajasthan",
  city: "Barmer",
  state: "Rajasthan",
  country: "India",
  languages: ["hi", "en", "raj"],
  rating: 4.9,
};

export const initialProducts: Product[] = [
  {
    id: "prod-101",
    artisan_id: "550e8400-e29b-41d4-a716-446655440000",
    title: "Handcrafted Jute Tote Bag",
    description: "Eco-friendly handwoven natural jute tote bag with reinforced cotton handles, traditional floral embroidery, and spacious capacity for daily shopping or events.",
    category: "Bags",
    material: "Natural Jute Fiber",
    craft_type: "Handwoven",
    tags: ["handmade", "eco-friendly", "jute", "bulk", "tote", "sustainable"],
    attributes: {
      color: "Natural Golden Brown",
      size: "Large (16x14 inches)",
      weight: "320g",
      capacity: "10-12 kg",
    },
    price: 750,
    currency: "INR",
    image_url: "https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=600",
    status: "published",
    available_quantity: 45,
    production_capacity: 150,
    created_at: "2026-09-01T10:00:00Z",
  },
  {
    id: "prod-102",
    artisan_id: "550e8400-e29b-41d4-a716-446655440000",
    title: "Terracotta Festive Oil Lamp Set",
    description: "Hand-moulded natural clay terracotta diyas with intricate geometric cutwork designed for festive illumination and sustainable home decor.",
    category: "Home Decor",
    material: "Riverbed Clay / Terracotta",
    craft_type: "Clay Pottery",
    tags: ["terracotta", "pottery", "diya", "lamp", "eco-decor", "festive"],
    attributes: {
      color: "Earthy Terracotta Red",
      size: "Medium (4 inches diameter)",
      pack: "Set of 6",
    },
    price: 480,
    currency: "INR",
    image_url: "https://images.unsplash.com/photo-1606293926075-69a00dbfde81?auto=format&fit=crop&q=80&w=600",
    status: "published",
    available_quantity: 60,
    production_capacity: 300,
    created_at: "2026-09-02T12:30:00Z",
  },
  {
    id: "prod-103",
    artisan_id: "550e8400-e29b-41d4-a716-446655440000",
    title: "Handblock Print Cotton Dupatta",
    description: "Breathable pure mulmul cotton dupatta featuring heritage floral bagru block printing crafted using authentic organic plant dyes.",
    category: "Textiles",
    material: "Organic Mulmul Cotton",
    craft_type: "Block Print",
    tags: ["blockprint", "cotton", "dupatta", "organic dye", "rajasthan craft"],
    attributes: {
      color: "Indigo & Ochre",
      length: "2.5 meters",
      wash_care: "Gentle cold hand wash",
    },
    price: 1150,
    currency: "INR",
    image_url: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=600",
    status: "published",
    available_quantity: 20,
    production_capacity: 80,
    created_at: "2026-08-28T09:15:00Z",
  },
  {
    id: "prod-104",
    artisan_id: "550e8400-e29b-41d4-a716-446655440000",
    title: "Handcrafted Cane & Bamboo Planter",
    description: "Durable woven natural cane planter basket with water-resistant inner lining suitable for indoor plants and balcony gardens.",
    category: "Home Decor",
    material: "Cane & Bamboo",
    craft_type: "Handwoven Basketry",
    tags: ["cane", "bamboo", "planter", "sustainable", "artisan made"],
    attributes: {
      color: "Natural Beige",
      diameter: "8 inches",
      height: "7 inches",
    },
    price: 650,
    currency: "INR",
    image_url: "https://images.unsplash.com/photo-1592150621744-aca64f48394a?auto=format&fit=crop&q=80&w=600",
    status: "published",
    available_quantity: 18,
    production_capacity: 70,
    created_at: "2026-08-25T14:00:00Z",
  },
];

export const mockQuoteRequests: QuoteRequestSummary[] = [
  {
    id: "quote-1",
    buyer_name: "Hotel Green Valley",
    buyer_type: "B2B Hospitality",
    requirement_title: "100 Jute Bags for Guest Welcome Kits",
    requirement_text: "Hotel Green Valley wants 100 Jute Bags for upcoming corporate delegates retreat. Custom print with eco ribbon preferred.",
    quantity: 100,
    budget_per_unit: 725,
    total_budget: 72500,
    status: "pending",
    time_ago: "~10m ago",
    is_new: true,
  },
  {
    id: "quote-2",
    buyer_name: "Crafty Corner Store",
    buyer_type: "B2B Retailer",
    requirement_title: "50 Terracotta Lamps for Diwali Collection",
    requirement_text: "Retail boutique seeking 50 handcrafted terracotta lamps with secure bubble packaging.",
    quantity: 50,
    budget_per_unit: 475,
    total_budget: 23750,
    status: "pending",
    time_ago: "1 day ago",
    is_new: false,
  },
  {
    id: "quote-3",
    buyer_name: "Ananya Lifestyle Boutique",
    buyer_type: "B2B Boutique",
    requirement_title: "30 Block Print Dupattas",
    requirement_text: "Need 30 pieces of indigo block printed mulmul dupattas for autumn collection.",
    quantity: 30,
    budget_per_unit: 1100,
    total_budget: 33000,
    status: "responded",
    time_ago: "4 days ago",
    is_new: false,
  },
];

export const mockOrders: OrderSummary[] = [
  {
    id: "ord-901",
    product_title: "Handwoven Table Mat (Set of 4)",
    image_url: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&q=80&w=300",
    quantity: 1,
    total_price: 1200,
    status: "delivered",
    date: "Delivered • 2 days ago",
  },
  {
    id: "ord-902",
    product_title: "Block Print Saree",
    image_url: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=300",
    quantity: 2,
    total_price: 2850,
    status: "processing",
    date: "Processing • Yesterday",
  },
  {
    id: "ord-903",
    product_title: "Clay Planter Set",
    image_url: "https://images.unsplash.com/photo-1592150621744-aca64f48394a?auto=format&fit=crop&q=80&w=300",
    quantity: 1,
    total_price: 650,
    status: "shipped",
    date: "Shipped • 3 days ago",
  },
];

export const mockActivities: ActivityItem[] = [
  {
    id: "act-1",
    title: "Handcrafted Basket",
    type: "order",
    time_ago: "2 days ago",
    status: "Order Received",
  },
  {
    id: "act-2",
    title: "Terracotta Lamp",
    type: "listed",
    time_ago: "5 days ago",
    status: "Listed",
  },
  {
    id: "act-3",
    title: "Block Print Dupatta",
    type: "quote",
    time_ago: "1 week ago",
    status: "Quote Request",
  },
];

